# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/blog/list?pageNo=0
Accept: application/json


###

POST http://localhost:8080/blog/create
Content-Type: application/json
Accept: application/json
JSESSIONID=CED0662D4FBDF222D5AC34990B995966

{
  "userId": 2,
  "blogDate": "2019-01-15",
  "blogText": "Wingardium leviosa"
}

###

PUT http://localhost:8080/blog/update?id=1
Content-Type: application/json
Accept: application/json
JSESSIONID=CED0662D4FBDF222D5AC34990B995966

{
  "blogDate": "2019-06-24",
  "blogText": "This text has been redacted AGAIN!",
  "userId": 1
}

###

DELETE http://localhost:8080/blog/delete?id=11
Accept: application/x-www-form-urlencoded

###