# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/user/1
Accept: application/json

###

POST http://localhost:8080/user/login
Content-Type: application/json
Accept: application/json

{
  "name": "admin",
  "password": "correct#Graphs1"
}

###

POST http://localhost:8080/user/login?name=placeholder&password=strep#Ports9
Content-Type: application/x-www-form-urlencoded

###

# "01kHV1K7qtp6Vp960GpH" test on pc
# "correct#Graphs1" test on laptop
# "strep#Ports9" test on laptop
